import React, { useEffect } from 'react';
import Header from '../common/Header';
import Footer from '../common/Footer';
import Navbar from '../common/Navbar';
import Image from 'next/image';
import Head from 'next/head';

const About = () => {
  return (
    <>
    <Head>
      <title>Next About Page</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <div className='bg-info'>
        <h2 >This is about file.</h2>
       
    </div>
    </>
  )
}

export default About
