import Head from 'next/head'
import Image from 'next/image'
// import Image from './Image'



function Home() {
  return (
    <div>
      <Head>
        <title>jeetendra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1 >
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p >
          Get started by editing{' '}
          <code >pages/index.js</code>
        </p>

     
      </main>

 
    </div>
  )
}

export default Home


